//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouteOptimization.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Addresses = new HashSet<Address>();
        }
    
        public int CityID { get; set; }
        public string Name { get; set; }
        public int ProvinceID { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual Province Province { get; set; }
    }
}
