//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouteOptimization.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int StoreID { get; set; }
        public string Name { get; set; }
        public string StoreNumber { get; set; }
        public int RetailerID { get; set; }
        public string EmailID { get; set; }
        public string Phone { get; set; }
        public int AddressID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Retailer Retailer { get; set; }
    }
}
